#!/bin/bash
# All storage reachable?
# REQUIRES: HERE, BUILTIN (pushd, popd)

FILES=
PROGS="echo wc"
/c/cs323/bin/Exist $FILES && exit

RUN="/c/cs323/bin/run -wall=2"
trap "/bin/rm -f $FILES; \
      /usr/bin/killall -q -u $USER -s KILL Bash $PROGS 2>/dev/null" 0 1 2 3 9 15
ulimit -u 1000

################
# Use version of reachable that ignores children

# HERE document
(/bin/echo "wc <<HERE" ;                \
 /bin/cat /c/cs323/Doc/Valgrind ;       \
 /bin/echo "HERE" ;                     \
 /bin/echo "echo End of test") |        \
/c/cs323/proj4/tests/reachable ./Bash |& \
/usr/bin/perl -p -e 's{ +}{ }g'         # Collapse multiple blanks from wc
echo

echo =====

# Directory stack
WHERE=`pwd`             # Where Bash is located
cd /
(/c/cs323/proj4/tests/reachable $WHERE/Bash <<\END >/dev/null) 2>&1
 pushd c
 pushd cs323
 pushd proj4
 popd
 pwd
 popd
 pwd
 popd
 pwd
 echo End of test
END
